name: mytorch
channels:
  - anaconda
  - https://repo.anaconda.com/pkgs/free
  - pytorch
  - conda-forge
  - abinit
  - matsci
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=0.9.0=py36_0
  - backports=1.0=py_2
  - backports.weakref=1.0rc1=py36_0
  - blinker=1.4=py_1
  - boto3=1.12.31
  - botocore=1.15.32
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.12.5
  - cachetools=3.1.1
  - certifi=2020.12.5
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.1
  - cmake=3.16.3
  - cryptography=2.8
  - docutils=0.15.2=py36_0
  - expat=2.2.9
  - ffmpeg=4.2
  - freetype=2.10.1
  - gettext=0.19.8.1
  - gmp=6.2.0
  - gnutls=3.6.5
  - google-auth=1.12.0
  - google-auth-oauthlib=0.4.1=py_2
  - h5py=2.10.0
  - hdf5=1.10.5
  - idna=2.9=py_1
  - jmespath=0.9.5=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c
  - krb5=1.16.4
  - lame=3.100
  - ld_impl_linux-ppc64le=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.68.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libflac=1.3.3
  - libgcc-ng=8.2.0
  - libgfortran-ng=8.2.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libogg=1.3.2
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libsndfile=1.0.28
  - libssh2=1.8.2
  - libstdcxx-ng=8.2.0
  - libtiff=4.1.0
  - libuv=1.34.0
  - libvorbis=1.3.6
  - libwebp-base=1.1.0
  - llvm-openmp=9.0.1
  - lz4-c=1.8.3
  - markdown=3.2.1
  - ncurses=6.1
  - nettle=3.4.1
  - ninja=1.10.0
  - numpy=1.18.1
  - oauthlib=3.0.1
  - olefile=0.46
  - openh264=1.8.0
  - openssl=1.1.1g
  - pillow=6.1.0
  - pip=20.0.2=py36_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pyjwt=1.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pysocks=1.7.1=py36h9f0ad1d_1
  - python=3.6.7
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pyyaml=5.3=py36h6eb9509_0
  - readline=8.0
  - requests=2.23.0
  - requests-oauthlib=1.2.0=py_0
  - rhash=1.3.6
  - rsa=4.0=py_0
  - s3transfer=0.3.3
  - sacremoses=0.0.42
  - scikit-learn=0.22.1
  - scipy=1.3.3
  - setuptools=45.2.0=py36_0
  - sqlite=3.30.1
  - tbb=2020.1
  - tk=8.6.10
  - typing=3.6.4=py36_0
  - urllib3=1.25.7=py36h9f0ad1d_1
  - werkzeug=1.0.0=py_0
  - wheel=0.34.2=py_1
  - x264=1!152.20180806
  - xz=5.2.4
  - yaml=0.2.2
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - apex==0.1
    - audioread==2.1.8
    - bleach==2.1
    - colorama==0.3.3
    - contextlib2==0.6.0.post1
    - ctcdecode==0.4
    - cycler==0.10.0
    - cython==0.29.21
    - dataclasses==0.7
    - decorator==4.4.2
    - dnspython==1.16.0
    - easydict==1.9
    - filelock==3.0.12
    - flask==1.1.2
    - grpcio==1.18.0
    - grpcio-tools==1.18.0
    - html5lib==1.1
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - jsonpatch==1.25
    - jsonpointer==2.0
    - kiwisolver==1.2.0
    - librosa==0.7.2
    - llvmlite==0.32.1
    - markupsafe==1.1.1
    - matplotlib==3.2.2
    - musdb==0.3.1
    - nats-bench==1.1
    - networkx==2.4
    - numba==0.49.1
    - onnx==1.8.1
    - opencv-python==4.5.1.48
    - pandas==1.1.0
    - protobuf==3.9.0
    - protobuf-compiler==1.0.20
    - pyaml==20.4.0
    - pybind11==2.5.0
    - pyparsing==2.4.7
    - python-etcd==0.4.5
    - python-levenshtein==0.12.0
    - pytz==2020.1
    - pyzmq==19.0.1
    - regex==2020.2.20
    - six==1.14.0
    - sklearn==0.0
    - soundfile==0.10.3.post1
    - sox==1.3.7
    - spotlight==1.0.8
    - stempeg==0.1.8
    - termcolor==1.1.0
    - texttable==1.6.3
    - tokenizers==0.5.2
    - torch==1.1.0
    - torch-baidu-ctc==0.3.0
    - torchelastic==0.2.0
    - torchfile==0.1.0
    - torchsummary==1.5.1
    - tornado==6.0.4
    - tqdm==4.31.1
    - transformers==2.5.1
    - typing-extensions==3.7.4.3
    - visdom==0.1.8.9
    - warpctc-pytorch==0.1
    - webencodings==0.5.1
    - websocket-client==0.57.0
    - wget==3.2

